spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.121.37:3306/boy?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 467246825
  #    dynamic:
#      primary: master
#      datasource:
#        master:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://118.24.121.37:3306/boy?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
#          username: root
#          password: 123456
#          type: com.zaxxer.hikari.HikariDataSource
#          hikari:
#            connection-timeout: 5000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
#            min-idle: 20                 # 最小连接数
#            max-pool-size: 30           # 最大连接数
#            auto-commit: true               # 自动提交
#            idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
#            max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
#            connection-test-query: SELECT 1
#        slave_1:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://118.24.121.37:3306/boy?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
#          username: root
#          password: 123456
#          type: com.zaxxer.hikari.HikariDataSource
#          hikari:
#            connection-timeout: 5000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
#            min-idle: 20                 # 最小连接数
#            max-pool-size: 30           # 最大连接数
#            auto-commit: true               # 自动提交
#            idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
#            max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
#            connection-test-query: SELECT 1
#        slave_2:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://118.24.121.37:3306/boy?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
#          username: root
#          password: 123456
#          type: com.zaxxer.hikari.HikariDataSource
#          hikari:
#            connection-timeout: 5000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
#            min-idle: 20                 # 最小连接数
#            max-pool-size: 30           # 最大连接数
#            auto-commit: true               # 自动提交
#            idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
#            max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
#            connection-test-query: SELECT 1
#  rabbitmq:
#    virtual-host: dev
#    host: 10.0.2.232
#    port: 5672
#    #addresses: 10.0.20.55:5670
#    username: dev
#    password: dev
#    publisher-confirms: true #开启发送失败返回
#    publisher-returns: false  #开启发送确认
#    listener:
#      simple:
#        #自动签收auto  手动 manual
#        acknowledge-mode: auto
#        #限流（海量数据，同时只能过来一条）
#        prefetch: 1


nacos:
  config:
    server-addr: 127.0.0.1:8848
  discovery:
    server-addr: 127.0.0.1:8848